image: python:3

pipelines:
  default:
    - step:
        script:
          - ssh $user@$server ls -l /home/$user
          - pip3 install -r requirements.txt
          - cd callback-catcher
          - python3 manage.py runserver 0.0.0.0:12443 --noreload
