image: python:3

pipelines:
  default:
    - step:
        name: Checking access
        script:
          - ssh $user@$server 'ls -l /home/$user' 
    - step:
        name: Clone
        script:
          - ssh $user@$server 'sh pull.sh'
    - step:
        name: Docker build
        script:
          - ssh $user@$server 'docker build --network host -t callback-catcher .'
    - step:
        name: Docker run
        script:
          - ssh $user@$server 'docker run -d callback-catcher'