version: "3"

services:
  mysql:
    container_name: db
    image: mariadb
    volumes:
        - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
        MYSQL_USER: "catcher"
        MYSQL_USER_PASSWORD: "password"
        MYSQL_ROOT_PASSWORD: "password"
        MYSQL_DATABASE: "catcher"

