version: "3"

services:
  db:
    container_name: db
    image: mariadb
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_USER: "catcher"
      MYSQL_USER_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "catcher"
    ports:
      - "127.0.0.1:3306:3306"

  catcher:
    container_name: catcher
    image: catcher
    build: .
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=1
    volumes:
      - ./logs:/catcher-app/logs
      - ./src/content:/catcher-app/content
      - ./src/files/ssl:/catcher-app/files/ssl
    environment:
      CATCHER_USERNAME: "admin"
      CATCHER_PASSWORD: "password"
      CATCHER_DOMAIN: "callbackcatcher.uk"
    ports:
      - "12443:12443"
    depends_on:
      - db
    network_mode: host
