version: "3"

services:
  db:
    container_name: db
    image: mariadb
    volumes:
        - ./mysql/data:/var/lib/mysql
    environment:
        MYSQL_USER: "catcher"
        MYSQL_USER_PASSWORD: "password"
        MYSQL_ROOT_PASSWORD: "password"
        MYSQL_DATABASE: "catcher"

  catcher:
    container_name: catcher
    image: catcher
    build: ./
    volumes:
      - /var/log/catcher/:/catcher-app/logs/
    ports:
      - "12443:12443"
    depends_on:
      - db
    links:
      - db
