# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-28 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fingerprint',
            table='fingerprints',
        ),
        migrations.AlterModelTable(
            name='handler',
            table='handlers',
        ),
        migrations.AlterModelTable(
            name='port',
            table='ports',
        ),
    ]
