# Generated by Django 2.1.7 on 2019-04-15 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 13, 50, 54, 821458, tzinfo=utc)),
        ),
    ]
