# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-28 12:01


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0002_auto_20180128_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('value', models.TextField()),
                ('callback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback', to='catcher.Callback')),
            ],
            options={
                'db_table': 'secrets',
            },
        ),
    ]
