# Generated by Django 2.1.7 on 2019-04-15 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0002_auto_20190415_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='token',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 13, 52, 53, 99444, tzinfo=utc)),
        ),
    ]
