# Generated by Django 2.1.7 on 2019-04-15 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0003_auto_20190415_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 13, 53, 53, 22554, tzinfo=utc)),
        ),
    ]
