# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-28 14:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0003_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='pid',
            field=models.IntegerField(null=True),
        ),
    ]
