# Generated by Django 2.1.7 on 2019-04-15 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0004_auto_20190415_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 14, 4, 47, 866597, tzinfo=utc)),
        ),
    ]
