# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 18:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0004_auto_20180128_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=32)),
                ('raw', models.TextField()),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.AlterField(
            model_name='callback',
            name='serverport',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='callback',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='enabled',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='port',
            name='expire_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='port',
            name='protocol',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='port',
            name='ssl',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='request',
            name='callback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catcher.Callback'),
        ),
    ]
