# Generated by Django 2.1.7 on 2019-04-15 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0005_auto_20190415_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 17, 48, 35, 192870, tzinfo=utc)),
        ),
    ]
