# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-12 15:01


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0005_auto_20180310_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='port',
            name='expire_time',
        ),
    ]
