# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0007_auto_20180312_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='callback',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catcher.Callback'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secret',
            name='callback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catcher.Callback'),
        ),
    ]
