# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0008_auto_20180313_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
