# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0010_auto_20180313_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbacktoken',
            name='found',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 3, 13, 17, 23, 4, 430914, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
