# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 12:33


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0012_auto_20180314_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callback',
            name='token',
        ),
        migrations.AddField(
            model_name='token',
            name='callback',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='catcher.Callback'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secret',
            name='callback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='catcher.Callback'),
        ),
    ]
