# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 12:55


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0013_auto_20180314_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='callback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='catcher.Callback'),
        ),
    ]
