# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 12:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0014_auto_20180314_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
