# Generated by Django 2.0.7 on 2018-08-29 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0015_auto_20180314_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='fingerprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catcher.Fingerprint'),
        ),
        migrations.AlterField(
            model_name='port',
            name='handler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catcher.Handler'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='callback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secrets', to='catcher.Callback'),
        ),
        migrations.AlterField(
            model_name='token',
            name='callback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='catcher.Callback'),
        ),
    ]
