# Generated by Django 2.0.7 on 2018-08-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0017_remove_callback_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='data',
            field=models.BinaryField(),
        ),
    ]
