# Generated by Django 2.0.7 on 2018-09-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0018_auto_20180829_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callback',
            old_name='data',
            new_name='session',
        ),
        migrations.AddField(
            model_name='callback',
            name='recieved',
            field=models.TextField(null=True),
        ),
    ]
