# Generated by Django 2.0.7 on 2018-09-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0019_auto_20180912_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callback',
            old_name='session',
            new_name='data',
        ),
    ]
