# Generated by Django 2.0.7 on 2018-09-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0020_auto_20180912_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callback',
            old_name='recieved',
            new_name='hexdata',
        ),
    ]
