# Generated by Django 2.0.7 on 2018-09-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0021_auto_20180912_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callback',
            old_name='hexdata',
            new_name='datahex',
        ),
    ]
