# Generated by Django 2.0.7 on 2018-09-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0022_auto_20180912_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('callback', models.ManyToManyField(related_name='searchhits', to='catcher.Callback')),
            ],
            options={
                'db_table': 'search',
            },
        ),
        migrations.RemoveField(
            model_name='token',
            name='callback',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
