# Generated by Django 2.0.7 on 2018-10-02 11:49

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0023_auto_20180913_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'blacklist',
            },
        ),
        migrations.RemoveField(
            model_name='search',
            name='callback',
        ),
        migrations.AlterField(
            model_name='handler',
            name='settings',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
